-- Camera Rental 数据库建表

CREATE TABLE IF NOT EXISTS cameras (
  id INT PRIMARY KEY AUTO_INCREMENT,
  model VARCHAR(100) NOT NULL,
  advantage VARCHAR(500) NOT NULL DEFAULT '',
  detail VARCHAR(500) DEFAULT '',
  image VARCHAR(500) DEFAULT '',
  price1day INT DEFAULT 0,
  price2day INT DEFAULT 0,
  price3dayPerDay INT DEFAULT 0,
  price5dayPerDay INT DEFAULT 0,
  price7day INT DEFAULT 0,
  hot TINYINT(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT PRIMARY KEY,
  cameraId INT NOT NULL,
  startDate DATE NOT NULL,
  endDate DATE NOT NULL,
  name VARCHAR(50) NOT NULL,
  school VARCHAR(100) NOT NULL,
  remark VARCHAR(500) DEFAULT '',
  phone VARCHAR(20) NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  renewNewEndDate DATE DEFAULT NULL,
  renewStatus VARCHAR(20) DEFAULT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_camera (cameraId),
  INDEX idx_phone (phone),
  INDEX idx_status (status),
  INDEX idx_start (startDate),
  INDEX idx_end (endDate)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY,
  username VARCHAR(50) NOT NULL DEFAULT '',
  password VARCHAR(100) NOT NULL DEFAULT '',
  phone VARCHAR(20) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX idx_phone (phone),
  INDEX idx_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT PRIMARY KEY,
  phone VARCHAR(20) NOT NULL,
  title VARCHAR(200) DEFAULT '',
  image VARCHAR(500) DEFAULT '',
  description VARCHAR(2000) NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_status (status),
  INDEX idx_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT PRIMARY KEY,
  content VARCHAR(2000) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS privacy (
  id INT PRIMARY KEY DEFAULT 1,
  content TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hero_config (
  id INT PRIMARY KEY DEFAULT 1,
  badge VARCHAR(200) DEFAULT '',
  title VARCHAR(500) DEFAULT '',
  subtitle VARCHAR(500) DEFAULT '',
  intervalSec INT DEFAULT 8,
  images TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reg_code (
  id INT PRIMARY KEY DEFAULT 1,
  code VARCHAR(20) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  role VARCHAR(20) DEFAULT 'admin',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_log (
  id BIGINT PRIMARY KEY,
  adminUser VARCHAR(50) NOT NULL,
  action VARCHAR(50) NOT NULL,
  target VARCHAR(200) DEFAULT '',
  detail VARCHAR(500) DEFAULT '',
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_admin (adminUser),
  INDEX idx_time (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS featured_config (
  id INT PRIMARY KEY DEFAULT 1,
  gallery_images TEXT,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO featured_config (id,gallery_images) VALUES (1,'');

CREATE TABLE IF NOT EXISTS camera_blocks (
  id INT PRIMARY KEY AUTO_INCREMENT,
  cameraId INT NOT NULL,
  startDate DATE NOT NULL,
  endDate DATE NOT NULL,
  blockType VARCHAR(20) DEFAULT 'buffer',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_camera (cameraId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sms_codes (
  phone VARCHAR(20) PRIMARY KEY,
  code VARCHAR(10) NOT NULL,
  expires BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
